---
- name: Gather facts
  when: ansible_facts is not defined
  ansible.builtin.setup:

- name: Install qemu_guest_agent
  when: ansible_system_vendor == 'QEMU'
  ansible.builtin.yum:
    name: qemu-guest-agent
    state: present
